# Generated by Django 2.0.6 on 2021-08-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('pk_bebidas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('pk_comida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('pk_menu', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_comida', models.CharField(max_length=20)),
                ('fk_Bebidas', models.ManyToManyField(to='webrestaurante.Bebidas')),
                ('fk_Comida', models.ManyToManyField(to='webrestaurante.Comida')),
            ],
        ),
        migrations.CreateModel(
            name='Postres',
            fields=[
                ('pk_postres', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='sell',
            name='fk_producto',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fk_producto',
        ),
        migrations.DeleteModel(
            name='producto',
        ),
        migrations.DeleteModel(
            name='sell',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.AddField(
            model_name='menu',
            name='fk_Postres',
            field=models.ManyToManyField(to='webrestaurante.Postres'),
        ),
    ]
