# Generated by Django 2.0.6 on 2021-08-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurante', '0002_auto_20210825_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='fk_Bebidas',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='fk_Comida',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='fk_Postres',
        ),
        migrations.DeleteModel(
            name='Bebidas',
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Postres',
        ),
    ]
