# Generated by Django 2.0.6 on 2021-08-25 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webrestaurante', '0007_auto_20210825_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='AComida',
            fields=[
                ('pk_comida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='BBebidas',
            fields=[
                ('pk_bebidas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='CPostres',
            fields=[
                ('pk_postres', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='DMenu',
            fields=[
                ('pk_menu', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_comida', models.CharField(max_length=20)),
                ('fk_Bebidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webrestaurante.BBebidas')),
                ('fk_Comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webrestaurante.AComida')),
                ('fk_Postres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webrestaurante.CPostres')),
            ],
        ),
    ]
