# Generated by Django 2.0.6 on 2021-08-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurante', '0008_acomida_bbebidas_cpostres_dmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmenu',
            name='fk_Bebidas',
        ),
        migrations.RemoveField(
            model_name='dmenu',
            name='fk_Comida',
        ),
        migrations.RemoveField(
            model_name='dmenu',
            name='fk_Postres',
        ),
        migrations.DeleteModel(
            name='AComida',
        ),
        migrations.DeleteModel(
            name='BBebidas',
        ),
        migrations.DeleteModel(
            name='CPostres',
        ),
        migrations.DeleteModel(
            name='DMenu',
        ),
    ]
