# Generated by Django 2.0.6 on 2021-09-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurante', '0010_auto_20210825_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas',
            name='precio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comida',
            name='precio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postres',
            name='precio',
            field=models.CharField(max_length=50),
        ),
    ]
