# Generated by Django 2.0.6 on 2021-09-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurante', '0013_auto_20210902_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='img',
            field=models.URLField(default='https://i.postimg.cc/KvByftfD/2417237.jpg', max_length=8000),
        ),
        migrations.AddField(
            model_name='comida',
            name='img',
            field=models.URLField(default='https://i.postimg.cc/KvByftfD/2417237.jpg', max_length=8000),
        ),
        migrations.AddField(
            model_name='postre',
            name='img',
            field=models.URLField(default='https://i.postimg.cc/KvByftfD/2417237.jpg', max_length=8000),
        ),
    ]
