# Generated by Django 2.0.6 on 2021-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurante', '0014_auto_20210908_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='img',
            field=models.URLField(default='https://i.postimg.cc/Hk439n1v/no-found.jpg', max_length=8000),
        ),
        migrations.AlterField(
            model_name='comida',
            name='img',
            field=models.URLField(default='https://i.postimg.cc/Hk439n1v/no-found.jpg', max_length=8000),
        ),
        migrations.AlterField(
            model_name='postre',
            name='img',
            field=models.URLField(default='https://i.postimg.cc/Hk439n1v/no-found.jpg', max_length=8000),
        ),
    ]
