# Generated by Django 2.0.6 on 2021-09-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurante', '0015_auto_20210908_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bebida',
            options={'ordering': ['nombre'], 'verbose_name': 'Bebida', 'verbose_name_plural': 'Bebidas'},
        ),
        migrations.AlterModelOptions(
            name='comida',
            options={'ordering': ['nombre'], 'verbose_name': 'Comida', 'verbose_name_plural': 'Comidas'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['tiempo_comida'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='postre',
            options={'ordering': ['nombre'], 'verbose_name': 'Postre', 'verbose_name_plural': 'Postres'},
        ),
    ]
