# Generated by Django 2.0.6 on 2021-09-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurante', '0017_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='img',
            field=models.URLField(default='https://i.postimg.cc/mkDjZsSb/5406010.jpg', max_length=8000),
        ),
        migrations.AlterField(
            model_name='comida',
            name='img',
            field=models.URLField(default='https://i.postimg.cc/sDGPTK60/51706.jpg', max_length=8000),
        ),
        migrations.AlterField(
            model_name='postre',
            name='img',
            field=models.URLField(default='https://i.postimg.cc/8kj0M2v2/3606.jpg', max_length=8000),
        ),
    ]
